version: "3"
services:
  database: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./database
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
  nginx: 
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev 
      context: ./nginx
    ports:
      - "3050:80"
  api: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=database
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app 